apiVersion: v1
kind: PersistentVolume

metadata:
  name: todo-images-pv

spec:
  storageClassName: todo-images-storage

  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  volumeMode: Filesystem

  local:
    path: /tmp/todo-images

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-server-0