apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: todo-images-claim

spec:
  storageClassName: todo-images-storage

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi