apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - manifests
  - storage
  - postgres
  - todo-app/manifests
  - todo-backend/manifests
  - todo-cronjob/manifests

images:

  - name: PROJECT/todo-app
    newName: us-east1-docker.pkg.dev/dwk-gke-502323/kubernetes/todo-app

  - name: PROJECT/todo-backend
    newName: us-east1-docker.pkg.dev/dwk-gke-502323/kubernetes/todo-backend

  - name: PROJECT/todo-cronjob
    newName: us-east1-docker.pkg.dev/dwk-gke-502323/kubernetes/todo-cronjob
