apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep

spec:
  replicas: 1

  selector:
    matchLabels:
      app: log-output

  template:
    metadata:
      labels:
        app: log-output

    spec:
      volumes:
        - name: shared-log
          persistentVolumeClaim:
            claimName: ping-log-claim

      containers:
        - name: log-writer
          image: log-output-writer:v2
          imagePullPolicy: Never

          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files

        - name: log-reader
          image: log-output-reader:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files