apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep

spec:
  replicas: 1

  selector:
    matchLabels:
      app: log-output

  template:
    metadata:
      labels:
        app: log-output

    spec:
      volumes:
        - name: shared-log
          emptyDir: {}

        - name: config-volume
          configMap:
            name: log-output-config

      containers:
        - name: writer
          image: log-output-writer:v2

          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files

        - name: reader
          image: log-output-reader:v2

          ports:
            - containerPort: 3000

          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE

          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files

            - name: config-volume
              mountPath: /usr/src/app/config