apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todo-app-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: todo-images-claim
      containers:
        - name: todo-app
          image: PROJECT/todo-app
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: todo-app-config
          volumeMounts:
            - name: image-storage
              mountPath: /usr/src/app/files