apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: exercises

resources:
- manifests
- postgres
- ping-pong/manifests

images:
- name: log-reader
  newName: log-reader
  newTag: d688b07012dd09094bd07af7597cc6a13de32637
- name: log-writer
  newName: log-writer
  newTag: d688b07012dd09094bd07af7597cc6a13de32637
- name: ping-pong
  newName: ping-pong
  newTag: d688b07012dd09094bd07af7597cc6a13de32637
